### PR TITLE
http to https

### PR DESCRIPTION
**Pull request by adititayal9**

### CODE REVIEW

**Comment by siddhant1** [comment]
@adititayal9 can you also update the changelog

**Review by siddhant1 — APPROVED** [review]
- Looks like we don't maintain the changelog

**Review by ad1992 — APPROVED** [review]
Also, can you update the commit message/pr title to `version bump for updating http to https in custom link plugin`

**Comment by ad1992** [comment]
> * Looks like we don't maintain the changelog

For ckeditor we dnt maintain a changelog as its forked repo and we hardly update it. But you can add the changes in https://github.com/interviewstreet/ckeditor-dev/blob/master/CHANGES.md#ckeditor-4-changelog @adititayal9

**Pull request merged**
